### ISSUE TITLE
Entering LoginAlpha, then runners connects indefinitely

### ISSUE THREAD

**Issue by aeroish** [fluofoxxo/outrun#23]
The game seems to make the initial connection but is hung on something.

**Comment by fluofoxxo** [comment]
Is there a printout of an error 'unexpected EOF?'

**Comment by aeroish** [comment]
I left it for roughly 10 minutes and the only printout I got was "Entering LoginAlpha" followed by "Done executing" shortly after. Outrun.db was generated without admin privileges, and running outrun.exe with admin privileges makes no difference as far as the connection goes.

**Comment by fluofoxxo** [comment]
If 'Done executing' appears shortly after LoginAlpha, the game should then move on to LoginDelta. Does the game give a generic connection error?

**Comment by aeroish** [comment]
When I opened this issue, it was just stuck connecting forever. Suddenly, now it is giving me the "connection failed" error, which I have not seen until now.

**Comment by fluofoxxo** [comment]
I would make sure that you're building the latest buildable commit. If the ring in the bottom right corner is frozen when connecting, it means that the server has sent data that is catastrophically incorrect, for one reason or another.
(If you'd like more timely discussion, feel free to [join the Discord.](https://discord.gg/fk4Q63). I'll make sure to post the fruits of your issue here to avoid [xkcd 979](https://xkcd.com/979/)!)

**Comment by aeroish** [comment]
It does not connect indefinitely anymore. Not sure what that was about...

I built the project earlier this morning, which means I missed out on three or four of your latest commits.

Another side note possibly worth mentioning, I am using default settings because I could not find any documentation on how to properly set up the config.json. Not sure if this would change anything.

**Comment by fluofoxxo** [comment]
¯\_(ツ)_/¯ Glad it's working now!

I apologize for the lack of documentation on config.json. If you're up to deciphering Go code, which I understand if you're not, [here's the relevant code for the configuration.](https://github.com/fluofoxxo/outrun/blob/master/config/parser.go#L26) Big ones are `port` and `doTimeLogging`, a string of numbers and boolean respectively, for changing port and whether or not to output time spent processing a request.

If your problem stays resolved, then we should close this issue.

**Comment by aeroish** [comment]
Whoops, maybe I should have been more clear. I meant that it is reaching the generic "connection failed" error now, just not connecting forever now.

I appreciate the information on config.json.

**Comment by fluofoxxo** [comment]
Oh, hmm. Could you kindly paste the complete log of outrun.exe to a pastebin like [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com] and share the link here? As well, is the ring icon in the bottom right stagnant or is it spinning?

**Comment by aeroish** [comment]
The ring icon is spinning. https://pastebin.com/C2rZvEr5

**Comment by fluofoxxo** [comment]
That's quite interesting. Are you using iOS or Android?

**Comment by aeroish** [comment]
Android. Real phone, not an emulator.

**Comment by fluofoxxo** [comment]
You can try reinstalling the APK used to connect to your instance and trying again. If that does not work, run the game until LoginAlpha, restart the game, then try playing again. If _that_ does not work, perhaps a rebuild of the project would be order, and at wits end, I may just provide an executable and see if it yields any difference.

**Comment by aeroish** [comment]
I tried all of your suggestions, and I had no luck. I guess it is worth asking if I possibly have missed any URL replacements in the CSharp dll?

**Comment by fluofoxxo** [comment]
NetBaseUtil.mActionServerUrlTable and NetBaseUtil.mSecureActionServerUrlTable should be populated by eleven strings, all the same, of the URI and port of your Outrun instance.
If you have an assets server you're pulling from, insert it into the strings in NetBaseUtil.mAssetURLTable and NetBaseUtil.mInformationURLTable. If you don't, feel free to set them to `http://pbassets.fluofoxxo.pw:9002/assets/` and `http://pbassets.fluofoxxo.pw:9002/information/` for mAssetURLTable and mInformationURLTable respectively.

**Comment by aeroish** [comment]
Alright, it looks like I haven't missed anything. I set up a game assets server; but I tried setting it to yours and even the Revival Project's, and it made no difference. I have been using your URL for the information URL as I am not entirely sure how to make one myself.

It might be worth sending that executable after all.

**Comment by fluofoxxo** [comment]
[Here's a download to an executable I've just built.](https://send.firefox.com/download/b262028d12024d03/#LWtu9bhMuS6l52ajhNr0eA) It'll be interesting if this does _or_ doesn't work...

**Comment by aeroish** [comment]
Unfortunately, no difference...

**Comment by fluofoxxo** [comment]
I think that rules out any issues as a result of Outrun.
This should narrow it down to either a firewall issue or an issue with how you're setting your URIs in Assembly-CSharp.
Try making an exception in Windows Firewall for the executable file, or perhaps run it on another system. If you're not lucky, make sure your URIs in Assembly-CSharp are correct, like the below example.
```cs
private static string[] mActionServerUrlTable = new string[]
{
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/"
};
private static string[] mSecureActionServerUrlTable = new string[]
{
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/",
    "http://domain.name:9001/"
};
private static string[] mAssetURLTable = new string[]
{
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/",
    "http://domain.name:9002/assets/"
};
private static string[] mInformationURLTable = new string[]
{
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/",
    "http://domain.name:9002/information/"
};
```
If everything is correct, I think we'd need to do some deeper analysis of any problems. I recommend installing [mitmproxy](https://docs.mitmproxy.org/stable/overview-installation/#installation-on-windows-via-pip3) and using the command `mitmweb -p 8888` to start a proxy, then using Android's network options to [set the proxy to your computer's local IP address and port 8888.](https://www.howtogeek.com/295048/how-to-configure-a-proxy-server-on-android/) Use the opened web interface from mitmweb and make sure the requests are going the correct way.
I apologize that there's no better way to debug an issue like this, I understand that it can be a bit complex.

**Comment by aeroish** [comment]
The game connects to a whole list of "noahapps" URLs, and then connects to the URL:9001/Login/login/. It does not attempt to connect to any other URLs, such as the asset or information URL.

**Comment by fluofoxxo** [comment]
The game should attempt to fetch http://<infoURL>:9002/assets/2.0.3_049/assetbundle/android/ablist.txt immediately after login. If it is not doing so, your connection to the asset server may be very weak. 
You should see if you can download that file, replacing infoURL with whatever asset/information server you are using, to your home computer with reasonable speed.

**Comment by aeroish** [comment]
I am currently using the Palmbound information server as I was not sure how to create my own. Is it the same or at least similar as the asset server? If you can guide me in making the information server, I will gladly try and see if that finally gets it working.

**Comment by fluofoxxo** [comment]
Doing a search for `"daguar" "sonic runners"` will yield a result from the Spanish website SonicParadise.net. You'll want the 'raw' files, as it is the full asset archive for Runners.
Running an HTTP server at the archive's directory `dl.sega-pc.com/srn/app/` will act as the asset server. If you've got Python 3 installed, you can enter the directory in a command prompt and run `python -m http.server 9002` to run an HTTP server on port 9002.

**Comment by aeroish** [comment]
It still isn't requesting the assets or information server at all..... The URLs are replaced 1:1 with your example.

**Comment by fluofoxxo** [comment]
That's incredibly strange. Does a stock [Palmbound APK](https://github.com/fluofoxxo/outrun#installation) work on your device?

**Comment by aeroish** [comment]
Yep. I was playing Palmbound not too long ago. Revival's APK works fine too.

Wait, question. With an APK uninstall, does the cache of Runners get wiped? I'm starting to wonder if it thinks I'm already an established player and is why it's getting confused...

**Comment by fluofoxxo** [comment]
APK uninstall should wipe the cache. You can tell if you're a fresh player if the number in the top left of the title screen says 0.

**Comment by aeroish** [comment]
Never mind, it works now! All it took was a restart of my phone..... 

You know, of course it was the simplest solution.

**Comment by fluofoxxo** [comment]
Darn, the one thing I legitimately thought, 'No, that can't be it!' Thanks for the information!
I'll close the issue.
