### ISSUE TITLE
I cannot get the client to work

### ISSUE THREAD

**Issue by Sidefix** [fluofoxxo/outrun#42]
Using a 2.0.3 client (2.0.3t) and an asset server, the client connects and seems to download assets, but then gets stuck at loading the actual game at 3%, no matter what I do.

No errors on the game server or asset servers.

Anyone have any insight into this?
Thanks in advance

**Comment by F121Live** [comment]
I assume that the game downloads the assets just fine, right?


A few notes: 
* Make sure you're using the assets version '2.0.3_049'
* Make sure you are pointing at the right server URL

**Comment by Sidefix** [comment]
@F121Live thanks for reaching back.

I suspect there may be an issue with the download, but I can't figure out where and / or why.

This is my data folder structure:
![image](https://user-images.githubusercontent.com/26040103/213135788-57ffa0b7-1fdf-48fa-a615-f9e527cfc73f.png)

And this is an example log output of my web server that's hosting the assets:
![image](https://user-images.githubusercontent.com/26040103/213138604-cac787f7-6e16-40c9-a9e1-487b6951e72b.png)

So the requests are clearly hitting the server.
Trying to access the resources through the browser also works:
![image](https://user-images.githubusercontent.com/26040103/213140945-d64f83d2-98b9-4a44-91bb-e2ba6ef03f87.png)

**Comment by Sidefix** [comment]
You can see the Assets folder/path in the above screenshots.

I'm not sure what else to check

**Comment by F121Live** [comment]
can you send a screenshot of the NetBaseUtil class? specifically the m_assetServerUrl array

**Comment by Sidefix** [comment]
Hi! I've discovered that the issue was with the client URL configured to hit the HTTPS endpoint instead of the HTTP; my logging on the webserver didn't pick up the protocol or the status code, hence my spinning around my own tail.

Solved. Thank you @F121Live very much for your involvement!
